# Generated by Django 5.0.2 on 2024-05-05 07:50

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
