# Generated by Django 5.0.2 on 2024-05-06 13:24

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
